version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  # - package-ecosystem: "pip"
  #   directory: "huak-py"
  #   schedule:
  #     interval: "weekly"
