[project]
name = "mock_project"
version = "0.0.1"
description = ""
dependencies = ["click==8.1.3"]
optional-dependencies = ["black==22.8.0"]

[[project.authors]]
name = "Chris Pryer"
email = "cnpryer@gmail.com"

[build-system]
requires = ["huak-core>=1.0.0"]
build-backend = "huak.core.build.api"
