[tool.huak]
name = "mock_project"
version = "0.0.1"
description = ""
authors = [""]

[tool.huak.dependencies]
click = "8.1.3"

[tool.huak.dev-dependencies]
black = "22.8.0"

[build-system]
requires = ["huak-core>=1.0.0"]
build-backend = "huak.core.build.api"
