name: Rust CI Pipeline
# This top level workflow controls the what and when of the CI pipeline for Rust components of huak

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/ci-rust.yaml'
  pull_request:
    branches:
      - "master"  
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/ci-rust.yaml'

jobs:
  run-rust-tests:
    uses: ./.github/workflows/test-rust.yaml
