name: Publish to PyPi
# Notes: This is just for the proof concept phase for huak

# ToDo: multi python version workflow

# ToDo: multi-platform workflow (container based)
#  openssl = { version = "0.10", features = ["vendored"] }
#  https://github.com/messense/maturin-action/discussions/78 ass openssl dep

on:
  push:
    branches:
      - '*' # for testing purposes
      #  release:
#    types: [published]

jobs:
  test-rust:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: pip install maturin==0.13.5
      - run: maturin publish --repository testpypi --username __token__ --password ${{ secrets.PYPI_PASSWORD }}
